# Generated by Django 5.0.1 on 2024-01-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffeine', '0002_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(blank=True, to='caffeine.product'),
        ),
    ]
